# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: flowinquiry
services:
  back-end:
    image: flowinquiry/flowinquiry-server:latest
    volumes:
      - ./volumes/storage/:/storage
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/flowinquiry
      - SPRING_DATASOURCE_USERNAME=flowinquiry
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgresql
    env_file:
      - ./.backend.env
  front-end:
    image: flowinquiry/flowinquiry-frontend:latest
    environment:
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_BASE_URL=https://localhost
      - BACK_END_URL=http://back-end:8080  # this value is the internal host of the back-end server that the front-end server side (NextJS server action) communicate with the back-end component
    env_file:
      - ./.frontend.env
  postgresql:
    image: postgres:16.3
    volumes:
      - ./volumes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=flowinquiry
      - POSTGRES_USER=flowinquiry
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - ./.backend.env
  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/certificate-authority:/data/caddy/pki/authorities/local
    ports:
      - '443:443'