[versions]
mapstructVersion = "1.5.5.Final"
archunitJunit5Version = "1.3.0"
springStateMachineVersion = "4.0.0"
lombokVersion = "1.18.34"
liquibaseVersion = "4.29.1"
assertJVersion = "3.26.3"
jcloudsVersion = "2.6.0"
dotEnvVersion = "3.0.0"
logbackVersion = "1.5.9"
junitVersion = "5.11.2"
mockitoVersion = "5.2.0"
mockitoJunitVersion = "5.14.1"
jsonApiVersion="2.1.3"

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version = "8.6.0" }
springdoc-openapi-starter-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version = "2.6.0" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
spring-statemachine-starter = { module = "org.springframework.statemachine:spring-statemachine-starter", version.ref = "springStateMachineVersion" }
spring-statemachine-jpa = { module = "org.springframework.statemachine:spring-statemachine-data-jpa", version.ref = "springStateMachineVersion" }
spring-statemachine-test = { module = "org.springframework.statemachine:spring-statemachine-test", version.ref = "springStateMachineVersion" }
liquibase = { module = "org.liquibase:liquibase-core", version.ref = "liquibaseVersion" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJVersion" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstructVersion" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstructVersion" }
jclouds = { module = "org.apache.jclouds:jclouds-all", version.ref = "jcloudsVersion" }
dot-env = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotEnvVersion" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitVersion" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
mockito = { module = "org.mockito:mockito-inline", version.ref = "mockitoVersion" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockitoJunitVersion" }
json-api = {module="jakarta.json:jakarta.json-api", version.ref="jsonApiVersion"}

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.4" }
openapi = { id = "org.springdoc.openapi-gradle-plugin", version = "1.9.0" }

[bundles]
spring-statemachine = ["spring-statemachine-starter", "spring-statemachine-jpa"]
logback = ["logback-classic"]
junit = ["junit-jupiter-api", "junit-jupiter-engine"]
mockito = ["mockito", "mockito-junit"]
