[versions]
mapstructVersion = "1.6.2"
archunitJunit5Version = "1.3.0"
springStateMachineVersion = "4.0.0"
lombokVersion = "1.18.34"
liquibaseVersion = "4.29.2"
assertJVersion = "3.26.3"
jcloudsVersion = "2.6.0"
dotEnvVersion = "3.0.0"
logbackVersion = "1.5.9"
junitVersion = "5.11.2"
mockitoVersion = "5.2.0"
mockitoJunitVersion = "5.14.1"
jsonApiVersion = "2.1.3"
parssonVersion="1.1.7"
springbootVersion = "3.3.4"
springDependencyManagementVersion="1.1.6"
jhisterVersion = "8.7.1"

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version.ref = "jhisterVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
spring-statemachine-starter = { module = "org.springframework.statemachine:spring-statemachine-starter", version.ref = "springStateMachineVersion" }
spring-statemachine-jpa = { module = "org.springframework.statemachine:spring-statemachine-data-jpa", version.ref = "springStateMachineVersion" }
spring-statemachine-test = { module = "org.springframework.statemachine:spring-statemachine-test", version.ref = "springStateMachineVersion" }
liquibase = { module = "org.liquibase:liquibase-core", version.ref = "liquibaseVersion" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJVersion" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstructVersion" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstructVersion" }
jclouds = { module = "org.apache.jclouds:jclouds-all", version.ref = "jcloudsVersion" }
dot-env = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotEnvVersion" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitVersion" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
mockito = { module = "org.mockito:mockito-inline", version.ref = "mockitoVersion" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockitoJunitVersion" }
json-api = { module = "jakarta.json:jakarta.json-api", version.ref = "jsonApiVersion" }
parsson = { module = "org.eclipse.parsson:parsson", version.ref = "parssonVersion" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springbootVersion" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref="springDependencyManagementVersion" }

[bundles]
spring-statemachine = ["spring-statemachine-starter", "spring-statemachine-jpa"]
logback = ["logback-classic"]
junit = ["junit-jupiter-api", "junit-jupiter-engine"]
mockito = ["mockito", "mockito-junit"]
json = ["json-api", "parsson"]
